"""Shared constants, namespace handling and role enums for the presentation plugin.

All plugin metadata is stored inside the SVG using a private XML namespace so it
survives save/reload in Inkscape and stays invisible to the renderer.
"""

# Private namespace for all plugin metadata.
PP_NS = "https://inkscape-pp-plugin/ns"
PP_PREFIX = "pp"


def register_ns():
    """Register the ``pp`` prefix with inkex so it is available everywhere.

    Safe to call multiple times. Attribute access still works via Clark
    notation (``{PP_NS}name``) regardless, but registering keeps the prefix
    stable and lets inkex resolve ``pp:name`` style names.
    """
    try:
        import inkex

        inkex.NSS.setdefault(PP_PREFIX, PP_NS)
    except Exception:
        # inkex not importable (e.g. pure-data unit tests) -- metadata access
        # via Clark notation still works without registration.
        pass


def cn(name):
    """Return the Clark-notation form of a plugin attribute name."""
    return "{%s}%s" % (PP_NS, name)


INKSCAPE_NS = "http://www.inkscape.org/namespaces/inkscape"
SODIPODI_NS = "http://sodipodi.sourceforge.net/DTD/sodipodi-0.0.dtd"


def ink(name):
    """Clark-notation form of an inkscape: namespaced attribute name."""
    return "{%s}%s" % (INKSCAPE_NS, name)


# ---------------------------------------------------------------------------
# Attribute names (used with the PP_NS namespace)
# ---------------------------------------------------------------------------
A_ROLE = "role"            # presentation | master | slide
A_SLIDE_ID = "slide-id"    # stable UUID linking a slide layer to its page
A_PAGE_ID = "page-id"      # mirror of slide-id on the page element
A_INDEX = "index"          # integer slide order (source of truth)
A_LAYOUT = "layout"        # layout key
A_MASTER = "master"        # id of the master applied to a slide
A_PH_ROLE = "ph-role"      # placeholder role
A_PH_ID = "ph-id"          # layout-local placeholder id
A_FIELD = "field"          # auto-updated field kind
A_MANAGED = "managed"      # "true" => generated by master apply (regenerable)
A_USER_EDITED = "user-edited"  # "true" => user changed it, protect from overwrite
A_MASTER_DEF = "master-def"    # JSON master definition (on master layer / root)
A_WEB_SRC = "web-src"          # URL embedded (iframe) for a web-content region
A_WEB_HTML = "web-html"        # inline HTML/JS embedded for a web-content region
A_CONTENT_KIND = "content-kind"  # web | html | mermaid | code | markdown
A_CONTENT_SRC = "content-src"    # source text (URL, code, mermaid or markdown)
A_CONTENT_LANG = "content-lang"  # language hint for code regions

# Presentation-level config (stored on the root <svg>)
A_ASPECT = "aspect"
A_FOOTER_TEXT = "footer-text"
A_DATE_MODE = "date-mode"   # fixed | today | none
A_DATE_VALUE = "date-value"
A_AUTHOR = "author"


# ---------------------------------------------------------------------------
# Role / kind enumerations (plain strings to keep SVG metadata human readable)
# ---------------------------------------------------------------------------
class Role:
    PRESENTATION = "presentation"
    MASTER = "master"
    SLIDE = "slide"


class PhRole:
    TITLE = "title"
    SUBTITLE = "subtitle"
    BODY = "body"
    FOOTER = "footer"
    SLIDENUMBER = "slidenumber"
    DATE = "date"
    LOGO = "logo"
    BACKGROUND = "background"
    WEBCONTENT = "webcontent"
    CONTENT = "content"


class ContentKind:
    WEB = "web"            # embed a URL via <iframe>
    HTML = "html"          # inline HTML/JS
    MERMAID = "mermaid"    # Mermaid diagram source
    CODE = "code"          # source-code snippet (syntax highlighted)
    MARKDOWN = "markdown"  # GitHub-flavoured Markdown


# CDN URLs for the in-browser renderers (used by the interactive SVG export).
# Bump versions here in one place.
CDN = {
    "mermaid": "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js",
    "marked": "https://cdn.jsdelivr.net/npm/marked/marked.min.js",
    "hljs": "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js",
    "hljs_css": "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/styles/github.min.css",
}


class Field:
    NUMBER = "number"
    TOTAL = "total"
    DATE = "date"
    FOOTER = "footer"


class LayoutKey:
    TITLE = "title"
    TITLE_CONTENT = "title_content"
    TWO_CONTENT = "two_content"
    BLANK = "blank"


class DateMode:
    FIXED = "fixed"
    TODAY = "today"
    NONE = "none"


# Default geometry helpers (fractions of page size)
DEFAULT_MARGIN = 0.06        # 6% page margin
TITLE_SAFE_INSET = 0.05      # 5% title-safe inset

# Standard slide sizes in user units (px) at 96dpi-ish logical resolution.
ASPECT_SIZES = {
    "16:9": (1920.0, 1080.0),
    "4:3": (1440.0, 1080.0),
}

# Gap between pages when tiled left-to-right on the canvas.
PAGE_GUTTER = 100.0
